In [4]:
import numpy as np

# DataTypes & Attributes

In [2]:
#Numpy has only one datatype "ndarray"
#ndarray has many attribiutes

In [5]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
ones.dtype

dtype('float64')

In [7]:
# Creating an array of a specific range
range_array = np.arange(0, 10, 2)

In [8]:
range_array

array([0, 2, 4, 6, 8])

In [9]:
# Creating a random array
rand_array = np.random.randint(0, 10, size=(3, 5))
rand_array

array([[9, 4, 3, 9, 2],
       [2, 8, 7, 4, 3],
       [9, 1, 6, 0, 0]])

In [19]:
# psudo random numbers

In [21]:
np.random.seed(seed = 0)
random_array_1 = np.random.randint(10, size=(3,5))
random_array_1

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [23]:
# Another method of creating an array of random numbers using numpy
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561],
       [0.77423369, 0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 , 0.61209572],
       [0.616934  , 0.94374808, 0.6818203 ]])

# Viewing Arrays and Matrices

In [24]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3]],

        [[4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2]],

        [[0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2]]],


       [[[9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8],
         [8, 8, 2, 3, 2]],

        [[0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8],
         [0, 8, 5, 9, 0]],

        [[9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9],
         [2, 8, 6, 6, 9]]]])

In [25]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [37]:
a4[:, :, :, :4]

array([[[[8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9],
         [4, 6, 4, 4]],

        [[4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0],
         [0, 1, 2, 4]],

        [[0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3],
         [2, 3, 4, 1]]],


       [[[9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3],
         [8, 8, 2, 3]],

        [[0, 8, 8, 3],
         [2, 8, 4, 3],
         [4, 3, 6, 9],
         [0, 8, 5, 9]],

        [[9, 6, 5, 3],
         [8, 0, 4, 9],
         [5, 7, 8, 8],
         [2, 8, 6, 6]]]])

# MANIPULATING THE MATRICES

## Arithematic Operations

In [38]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [39]:
ones = np.ones(3)

In [40]:
a1 + ones

array([2., 3., 4.])

In [41]:
a1 - ones

array([0., 1., 2.])

In [43]:
a2 = np.array([[1, 2, 3.3],
             [4., 10.5, 19.5]])


In [44]:
a2

array([[ 1. ,  2. ,  3.3],
       [ 4. , 10.5, 19.5]])

In [48]:
a2

array([[ 1. ,  2. ,  3.3],
       [ 4. , 10.5, 19.5]])

In [49]:
np.square(a2)

array([[  1.  ,   4.  ,  10.89],
       [ 16.  , 110.25, 380.25]])

In [50]:
#MOD
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 0.5, 1.5]])

In [51]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [52]:
np.exp(a2)

array([[2.71828183e+00, 7.38905610e+00, 2.71126389e+01],
       [5.45981500e+01, 3.63155027e+04, 2.94267566e+08]])

In [53]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [58]:
#Creating a massive array
massive_array = np.random.random(1000)
massive_array[:10]

array([0.81922614, 0.94551446, 0.12975713, 0.35431267, 0.37758386,
       0.07987885, 0.5011568 , 0.02229736, 0.13672066, 0.54215489])

In [59]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

237 µs ± 43.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
11.5 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
